services:
  webaetz:
    build:
      context: .
    ports:
      - "443:443"
    environment:
      DB_HOST: "postgres"  # IP базы данных
      DB_PORT: "5432"
      DB_USER: 'baha'
      DB_PASSWORD: 'adminadmin1'
      DB_NAME: binai
